// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3W4MEw9bWUbPsUyz_z-PkCotyKpBWXcI',
    appId: '1:192387553653:web:1763778410957898785b3c',
    messagingSenderId: '192387553653',
    projectId: 'heartdisesesapp',
    authDomain: 'heartdisesesapp.firebaseapp.com',
    storageBucket: 'heartdisesesapp.firebasestorage.app',
    measurementId: 'G-SVJ65RWJ8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ6jGBveCx77leJ1ZtS0rj5W5MGvYN9Cg',
    appId: '1:192387553653:android:25c420ee543d65f9785b3c',
    messagingSenderId: '192387553653',
    projectId: 'heartdisesesapp',
    storageBucket: 'heartdisesesapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVl4I0s2r8WFdC0fglFDTIZY0lUH7CYPw',
    appId: '1:192387553653:ios:cb3dff758cfe29b4785b3c',
    messagingSenderId: '192387553653',
    projectId: 'heartdisesesapp',
    storageBucket: 'heartdisesesapp.firebasestorage.app',
    iosBundleId: 'com.example.heartDisesesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVl4I0s2r8WFdC0fglFDTIZY0lUH7CYPw',
    appId: '1:192387553653:ios:cb3dff758cfe29b4785b3c',
    messagingSenderId: '192387553653',
    projectId: 'heartdisesesapp',
    storageBucket: 'heartdisesesapp.firebasestorage.app',
    iosBundleId: 'com.example.heartDisesesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3W4MEw9bWUbPsUyz_z-PkCotyKpBWXcI',
    appId: '1:192387553653:web:9a53f6622926e8df785b3c',
    messagingSenderId: '192387553653',
    projectId: 'heartdisesesapp',
    authDomain: 'heartdisesesapp.firebaseapp.com',
    storageBucket: 'heartdisesesapp.firebasestorage.app',
    measurementId: 'G-81SLHL6NHK',
  );
}
